### PR TITLE
fixed ipify url

### PR DESCRIPTION
**Pull request by gigantino**

### CODE REVIEW

**Comment by gigantino** [comment]
#30

**Comment by Edouard127** [comment]
Why would an ipv6 fix the issue ?

**Comment by gigantino** [comment]
> Why would an ipv6 fix the issue ?

It's not an ipv6. The old url simply doesn't work and times out...

**Comment by Edouard127** [comment]
But It do works for me

**Comment by gigantino** [comment]
> But It do works for me

Just tried with a VPN. My European IP got blocked even on the first request. An American IP goes through.
Maybe if the request fails with the first IP it could try with the second one?

**Comment by gigantino** [comment]
the commit 4235315ed080688101c7677164ebfbec3bcc308c solved the issue

**Pull request closed without merging**
